package android.smartcampus.template.standalone;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ATLETA.
 */
public class Atleta {

    private Long id;
    private String nome;
    private String cognome;
    private String nazionalita;

    public Atleta() {
    }

    public Atleta(Long id) {
        this.id = id;
    }

    public Atleta(Long id, String nome, String cognome, String nazionalita) {
        this.id = id;
        this.nome = nome;
        this.cognome = cognome;
        this.nazionalita = nazionalita;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getCognome() {
        return cognome;
    }

    public void setCognome(String cognome) {
        this.cognome = cognome;
    }

    public String getNazionalita() {
        return nazionalita;
    }

    public void setNazionalita(String nazionalita) {
        this.nazionalita = nazionalita;
    }

}
