package android.smartcampus.template.standalone;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.IdentityScopeType;

import android.smartcampus.template.standalone.UtenteDao;
import android.smartcampus.template.standalone.EventoDao;
import android.smartcampus.template.standalone.MeetingDao;
import android.smartcampus.template.standalone.POIDao;
import android.smartcampus.template.standalone.TicketDao;
import android.smartcampus.template.standalone.AtletaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        UtenteDao.createTable(db, ifNotExists);
        EventoDao.createTable(db, ifNotExists);
        MeetingDao.createTable(db, ifNotExists);
        POIDao.createTable(db, ifNotExists);
        TicketDao.createTable(db, ifNotExists);
        AtletaDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        UtenteDao.dropTable(db, ifExists);
        EventoDao.dropTable(db, ifExists);
        MeetingDao.dropTable(db, ifExists);
        POIDao.dropTable(db, ifExists);
        TicketDao.dropTable(db, ifExists);
        AtletaDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(UtenteDao.class);
        registerDaoClass(EventoDao.class);
        registerDaoClass(MeetingDao.class);
        registerDaoClass(POIDao.class);
        registerDaoClass(TicketDao.class);
        registerDaoClass(AtletaDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
