package android.smartcampus.template.standalone;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.Serializable;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.ProtocolException;
import java.net.URL;
import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import android.graphics.Bitmap;
import android.os.AsyncTask;
import android.text.Html;

import smartcampus.android.template.universiadi.R;
import smartcampus.android.template.standalone.Utilities.ElementDescRoute;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EVENTO.
 */
public class Evento implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private String nome;
	private Long data;
	private Long oraInizio;
	private Long oraFine;

	private String descrizione;
	private Double latGPS;
	private Double lngGPS;
	private String tipoSport;
	private byte[] image;

	public Evento() {
	}

	public Evento(Long id) {
		this.id = id;
	}

	public Evento(Long id, String nome, Long data, Long oraInizio,
			Long oraFine, String descrizione, Double latGPS, Double lngGPS,
			String tipoSport, byte[] image) {
		super();
		this.id = id;
		this.nome = nome;
		this.data = data;
		this.oraInizio = oraInizio;
		this.oraFine = oraFine;
		this.descrizione = descrizione;
		this.latGPS = latGPS;
		this.lngGPS = lngGPS;
		this.tipoSport = tipoSport;
		this.image = image;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Long getData() {
		return data;
	}

	public void setData(Long data) {
		this.data = data;
	}

	public String getDescrizione() {
		return descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Double getLatGPS() {
		return latGPS;
	}

	public void setLatGPS(Double latGPS) {
		this.latGPS = latGPS;
	}

	public Double getLngGPS() {
		return lngGPS;
	}

	public void setLngGPS(Double lngGPS) {
		this.lngGPS = lngGPS;
	}

	public String getTipoSport() {
		return tipoSport;
	}

	public void setTipoSport(String tipoSport) {
		this.tipoSport = tipoSport;
	}

	public Long getOraInizio() {
		return oraInizio;
	}

	public void setOraInizio(Long oraInizio) {
		this.oraInizio = oraInizio;
	}

	public Long getOraFine() {
		return oraFine;
	}

	public void setOraFine(Long oraFine) {
		this.oraFine = oraFine;
	}

	public byte[] getImage() {
		return image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}
}
