package android.smartcampus.template.standalone;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MEETING.
 */
public class Meeting {

    private Long id;
    private String nome;
    private Long data;
    private String descrizione;
    private Double latGPS;
    private Double lngGPS;
    private String ambito;
    private String ruolo;

    public Meeting() {
    }

    public Meeting(Long id) {
        this.id = id;
    }

    public Meeting(Long id, String nome, Long data, String descrizione, Double latGPS, Double lngGPS, String ambito, String ruolo) {
        this.id = id;
        this.nome = nome;
        this.data = data;
        this.descrizione = descrizione;
        this.latGPS = latGPS;
        this.lngGPS = lngGPS;
        this.ambito = ambito;
        this.ruolo = ruolo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Long getData() {
        return data;
    }

    public void setData(Long data) {
        this.data = data;
    }

    public String getDescrizione() {
        return descrizione;
    }

    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    public Double getLatGPS() {
        return latGPS;
    }

    public void setLatGPS(Double latGPS) {
        this.latGPS = latGPS;
    }

    public Double getLngGPS() {
        return lngGPS;
    }

    public void setLngGPS(Double lngGPS) {
        this.lngGPS = lngGPS;
    }

    public String getAmbito() {
        return ambito;
    }

    public void setAmbito(String ambito) {
        this.ambito = ambito;
    }

    public String getRuolo() {
        return ruolo;
    }

    public void setRuolo(String ruolo) {
        this.ruolo = ruolo;
    }

}
