package android.smartcampus.template.standalone;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SPORT.
 */
public class Sport {

    private String nome;
    private byte[] immagine;
    private String descrizione;

    public Sport() {
    }

    public Sport(String nome) {
        this.nome = nome;
    }

    public Sport(String nome, byte[] immagine, String descrizione) {
        this.nome = nome;
        this.immagine = immagine;
        this.descrizione = descrizione;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public byte[] getImmagine() {
        return immagine;
    }

    public void setImmagine(byte[] immagine) {
        this.immagine = immagine;
    }

    public String getDescrizione() {
        return descrizione;
    }

    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

}
