package android.smartcampus.template.standalone;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;

import android.smartcampus.template.standalone.Sport;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SPORT.
*/
public class SportDao extends AbstractDao<Sport, Long> {

    public static final String TABLENAME = "SPORT";

    /**
     * Properties of entity Sport.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property LatGPS = new Property(1, Double.class, "latGPS", false, "LAT_GPS");
        public final static Property LngGPS = new Property(2, Double.class, "lngGPS", false, "LNG_GPS");
        public final static Property Immagine = new Property(3, byte[].class, "immagine", false, "IMMAGINE");
        public final static Property Descrizione = new Property(4, String.class, "descrizione", false, "DESCRIZIONE");
        public final static Property Atleti = new Property(5, Long.class, "atleti", false, "ATLETI");
    };

    private DaoSession daoSession;


    public SportDao(DaoConfig config) {
        super(config);
    }
    
    public SportDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SPORT' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'LAT_GPS' REAL," + // 1: latGPS
                "'LNG_GPS' REAL," + // 2: lngGPS
                "'IMMAGINE' BLOB," + // 3: immagine
                "'DESCRIZIONE' TEXT," + // 4: descrizione
                "'ATLETI' INTEGER);"); // 5: atleti
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SPORT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Sport entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Double latGPS = entity.getLatGPS();
        if (latGPS != null) {
            stmt.bindDouble(2, latGPS);
        }
 
        Double lngGPS = entity.getLngGPS();
        if (lngGPS != null) {
            stmt.bindDouble(3, lngGPS);
        }
 
        byte[] immagine = entity.getImmagine();
        if (immagine != null) {
            stmt.bindBlob(4, immagine);
        }
 
        String descrizione = entity.getDescrizione();
        if (descrizione != null) {
            stmt.bindString(5, descrizione);
        }
 
        Long atleti = entity.getAtleti();
        if (atleti != null) {
            stmt.bindLong(6, atleti);
        }
    }

    @Override
    protected void attachEntity(Sport entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Sport readEntity(Cursor cursor, int offset) {
        Sport entity = new Sport( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getDouble(offset + 1), // latGPS
            cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2), // lngGPS
            cursor.isNull(offset + 3) ? null : cursor.getBlob(offset + 3), // immagine
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // descrizione
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5) // atleti
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Sport entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLatGPS(cursor.isNull(offset + 1) ? null : cursor.getDouble(offset + 1));
        entity.setLngGPS(cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2));
        entity.setImmagine(cursor.isNull(offset + 3) ? null : cursor.getBlob(offset + 3));
        entity.setDescrizione(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setAtleti(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Sport entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Sport entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
