package android.smartcampus.template.standalone;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TICKET.
 */
public class Ticket {

    private Double latGPS;
    private Double lngGPS;
    private String descrizione;
    private String categoria;
    private String foto;

    public Ticket() {
    }

    public Ticket(Double latGPS, Double lngGPS, String descrizione, String categoria, String foto) {
        this.latGPS = latGPS;
        this.lngGPS = lngGPS;
        this.descrizione = descrizione;
        this.categoria = categoria;
        this.foto = foto;
    }

    public Double getLatGPS() {
        return latGPS;
    }

    public void setLatGPS(Double latGPS) {
        this.latGPS = latGPS;
    }

    public Double getLngGPS() {
        return lngGPS;
    }

    public void setLngGPS(Double lngGPS) {
        this.lngGPS = lngGPS;
    }

    public String getDescrizione() {
        return descrizione;
    }

    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    public String getCategoria() {
        return categoria;
    }

    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    public String getFoto() {
        return foto;
    }

    public void setFoto(String foto) {
        this.foto = foto;
    }

}
