package android.smartcampus.template.standalone;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table UTENTE.
 */
public class UtenteSuperiore {

    private String nome;
    private String cognome;
    private String ruolo;
    private String ambito;
    private byte[] foto;
    private String numeroTelefonico;
    private String mail;
    private String id;
    private String uuid;
    
   
    
	public UtenteSuperiore(String nome, String cognome, String ruolo, String ambito,
			byte[] foto, String numeroTelefonico, String mail, String id,
			String uuid) {
		super();
		this.nome = nome;
		this.cognome = cognome;
		this.ruolo = ruolo;
		this.ambito = ambito;
		this.foto = foto;
		this.numeroTelefonico = numeroTelefonico;
		this.mail = mail;
		this.id = id;
		this.uuid = uuid;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getCognome() {
		return cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	public String getRuolo() {
		return ruolo;
	}

	public void setRuolo(String ruolo) {
		this.ruolo = ruolo;
	}

	public String getAmbito() {
		return ambito;
	}

	public void setAmbito(String ambito) {
		this.ambito = ambito;
	}

	public byte[] getFoto() {
		return foto;
	}

	public void setFoto(byte[] foto) {
		this.foto = foto;
	}

	public String getNumeroTelefonico() {
		return numeroTelefonico;
	}

	public void setNumeroTelefonico(String numeroTelefonico) {
		this.numeroTelefonico = numeroTelefonico;
	}

	public String getMail() {
		return mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
}
